### ISSUE TITLE
Missing dockwidget icons

### ISSUE THREAD

**Issue by VFLashM** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#13]
`darkstyle.qss` refers to `:/darkstyle/icon_window_close.png` and `:/darkstyle/icon_window_close.png` which don't exist. Apparently it was intended to refer to `:/image/*`.

**Comment by Jorgen-VikingGod** [comment]
thx for the hint.
That's right - before I had only one resource file and split it later by style and window class.
There are two ways to solve this:
* replace :/darkstyle/icon_window_close.png by :/darkstyle/icon_close.png
* replace :/darkstyle/icon_window_restore.png by :/darkstyle/icon_undock.png

or copy icons also to the darkstyle content

**Comment by VFLashM** [comment]
That's exactly how I fixed it.
Speaking of, it seems that it was intended for darkstyle to refer resources in framelesswindow. That dependency would be a minor hassle for and others who don't use frameless window. Might be better to keep them separate or event add third, shared resources file.
