### ISSUE TITLE
Names of tabbed DockWidgets are very dark

### ISSUE THREAD

**Issue by VFLashM** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#14]
I think tabbed dock widgets still use default text color.
Not sure if that's intended, but they are pretty hard to read.

**Comment by Jorgen-VikingGod** [comment]
@VFLashM do you have a screenshot?
On which OS did you try it?

**Comment by VFLashM** [comment]
It was on MacOSX, Qt 5.10.
Here's the screenshot:

![unnamed](https://user-images.githubusercontent.com/3723853/35370460-f3f98dde-015b-11e8-92a6-293fa2d2dd4b.png)

I fixed it by adding this line:
```
QTabBar::tab{
+  color:#aaaaaa;
}
```

**Comment by Jorgen-VikingGod** [comment]
looks weird...
My is looking correctly (also MacOS + Qt 5.10) - tabbed dock widgets on the right and normal tabs on the left:
<img width="559" alt="screen shot 2018-01-25 at 05 26 04" src="https://user-images.githubusercontent.com/6171589/35370772-4d8f48dc-0190-11e8-88ac-352405e45255.png">

**Comment by Jorgen-VikingGod** [comment]
Looks like you did not apply the correct palette to the application.

**Comment by VFLashM** [comment]
Maybe it has something to do with the fact that it was docked widget, I
don't know.
Do I need to do something more than style? I thought it sets palette on its
own.

setStyle(new DarkStyle);

**Comment by Jorgen-VikingGod** [comment]
This is exactly the way to use it.
Really strange issue.

Can you report that this example is working?
See my referenced commit

**Comment by VFLashM** [comment]
Does not reproduce. I guess in my case it happened because I apply style
after creating widgets.

**Comment by Jorgen-VikingGod** [comment]
really strange happens here. But good to know, that it is fixed now for your application.
If it appears again, please open a new issue.
