### ISSUE TITLE
Title of QGroupBox overlaps content

### ISSUE THREAD

**Issue by JoseTomasTocino** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#16]
Thanks for the theme, it looks gorgeous. However there's an issue that appears in the screenshots in the README file: the title of the QGroupBox elements slightly overlaps the content. Here's a capture (brightness is enhanced to improve visibility):

![image](https://user-images.githubusercontent.com/648833/38088512-595a6536-335c-11e8-868c-6a16ccc4eafb.png)

Is that intended? Do you know how it could be fixed?

**Comment by Jorgen-VikingGod** [comment]
Thx for reporting. 
Did not see this dirty overlap.
Now it is nice again. You only have to change the [margin-top of GroupBox](https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle/blob/master/darkstyle/darkstyle.qss#L134)
