### ISSUE TITLE
Maximize on second screen

### ISSUE THREAD

**Issue by Oviglo** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#17]
Hello,
I have a probleme when I maximize the window in a second screen, the window clip many time before maximize.

Thanks for your great theme.

**Comment by sherrygopal** [comment]
I am not expert programmer. I had same issue on clicking Maximize it does some artifacts and then makes it full screen. However I resolved it by changing the line 184 in framlesswindow.cpp
Before:    `setWindowState(Qt::WindowMaximized);`
After:      `setWindowState(Qt::WindowFullScreen);`

Hope this helps.

**Comment by Jorgen-VikingGod** [comment]
@sherrygopal Qt::WindowFullScreen is not the same as Qt::WindowMaximized, but I'm fine with fullscreen too.
