### ISSUE TITLE
How to window's icon?

### ISSUE THREAD

**Issue by ysx1993** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#18]
Hi Jorgen! 
Can you reimplement the setWindowIcon function so that I can set the icon in the window's title bar?

**Comment by Jorgen-VikingGod** [comment]
hi @ysx1993 should be a minor change.
Hope I can dig into it on weekend...

**Comment by ysx1993** [comment]
Thank you very much Jorgen！

**Comment by Jorgen-VikingGod** [comment]
@ysx1993 can you try my changes?
you can now use `framelessWindow.setWindowIcon(your_icon);`

**Comment by ysx1993** [comment]
Hi Jorgen!
It's so cool! Thanks your changes^ ^!

**Comment by ysx1993** [comment]
Why the title label hide when window restored and title label show again when window maximized?

**Comment by ysx1993** [comment]
![restored](https://user-images.githubusercontent.com/12573603/39792607-053a7e68-5374-11e8-91e7-ab9f1a417beb.png)
![maxi](https://user-images.githubusercontent.com/12573603/39792615-0db1e7b6-5374-11e8-9ee6-c67a72285af5.png)

**Comment by Jorgen-VikingGod** [comment]
@ysx1993 good question, did not now this effect. Will try it later on an Windows-PC, maybe it is a bug on Windows. On my Mac everything is fine.

**Comment by ysx1993** [comment]
I have fixed this bug by remove title text shadow effect in construct…

**Comment by ysx1993** [comment]
Hi Jorgen！
I think that the window icon should be hidden first, and then be displayed when setWindowIcon is called, so that it will not cause the left margin of the title text.

**Comment by ysx1993** [comment]
Thanks Jorgen, it works fine.

**Comment by Jorgen-VikingGod** [comment]
would you please push a new commit with this change to your pull request - so I can merge it into master. Thx

**Comment by ysx1993** [comment]
Okay!

**Comment by Jorgen-VikingGod** [comment]
this issue was fixed by pull request #23 
thx for your support!
