### ISSUE TITLE
Cannot fill the screen in Qt5.4(MSVC2013) when the window is maximized 

### ISSUE THREAD

**Issue by ysx1993** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#19]
I have fixed this bug by call setMargin(15) in on_restoreButton_clicked function and setMargin(0) in on_maximizeButton_clicked function.

.

**Comment by Jorgen-VikingGod** [comment]
this is really strange, because I do this already in 
[FramelessWindow::styleWindow](https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle/blob/master/framelesswindow/framelesswindow.cpp#L74)

**Comment by ysx1993** [comment]
I felt strange at the time, but when I don't add the setMargin function, the maximized window will have a 15px margin (if it is out of focus, it will fill the screen again)

**Comment by ysx1993** [comment]
Bug...
![bug](https://user-images.githubusercontent.com/12573603/39765212-e380ec2c-5313-11e8-931f-911886a16acb.png)

**Comment by ysx1993** [comment]
Solution...
![solve](https://user-images.githubusercontent.com/12573603/39765295-1435ec82-5314-11e8-9ee8-afedf111b9f6.png)

**Comment by Jorgen-VikingGod** [comment]
can you push a pull request with your changes?

**Comment by ysx1993** [comment]
Hi Jorgen!
I have pushed my pull request to you, you can check it!
