### ISSUE TITLE
"ui_framelesswindow.h": no such file or directory

### ISSUE THREAD

**Issue by Hausmeistar** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#25]
Hello there, since I'm new to qt please don't be too harsh to me here.
The project looks really good so I followed the given steps as shown in the readme file.
The following outcome is as shown in the Screenshot.

> "ui_framelesswindow.h": no such file or directory
![screenshot_1193](https://user-images.githubusercontent.com/39679488/40590344-6d65ad9a-61fd-11e8-9b4d-ecf06da958eb.png)
Simple project as I have it right now
[DesktopControl.zip](https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle/files/2042981/DesktopControl.zip)

**Comment by Jorgen-VikingGod** [comment]
Hi @Hausmeistar how do compile your project?
In case you do not use QtCreator or VS+VSTools, you have to manually generate some files for moc, ui and qrc.

**Comment by iyop45** [comment]
I have followed all the steps and I am getting the same error. I am using QtCreator. Can you point me in the right direction on how to generate the files manually?

**Comment by Jorgen-VikingGod** [comment]
normally QtCreater will run uic tool to generate ui_*.h files depending on the project file:
https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle/blob/master/frameless_window_dark.pro#L34-L35

If this is not working, than maybe your QtCreator is not correctly configured?
Did you try another project with form (ui) files?

**Comment by Jorgen-VikingGod** [comment]
I reconstruct the way of using the ui and this hopefully should work now for everyone

**Comment by Hausmeistar** [comment]
It is working now. Thank you very much.

**Comment by Jorgen-VikingGod** [comment]
great to hear. You're welcome
