### ISSUE TITLE
Deprecated API in use

### ISSUE THREAD

**Issue by mtakala** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#37]
The framelesswindow uses a deprecated Qt API. While I did not check what will happen in Qt 5.14, I think there should be an effort to reduce the amount of old API.

QApplication::desktop()->isVirtualDesktop())
`warning: 'bool QDesktopWidget::isVirtualDesktop() const' is deprecated: Use QScreen::virtualSiblings() of primary screen [-Wdeprecated-declarations]
     if (QApplication::desktop()->isVirtualDesktop()) {`
                                                   ^

**Comment by Jorgen-VikingGod** [comment]
Thx for reporting. I do not have the time to maintain this issue now. Would be great if you can create a pull request.

**Comment by mtakala** [comment]
Made a pull request. Seems to work on 1-display windows system. I will be able to test on multiple display system with different resolutions next week. I would appreciate if there was a quicker tester than me.... or a unit test.
