### ISSUE TITLE
Qt::WindowMinimizeButtonHint makes a window non-frameless

### ISSUE THREAD

**Issue by chaosink** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#4]
OS: Linux Mint 18.2 Cinnamon 64-bit

Qt Creator 4.3.1
Based on Qt 5.9.1 (GCC 5.3.1 20160406 (Red Hat 5.3.1-6), 64 bit)

In my environment, a window with the flag `Qt::WindowMinimizeButtonHint` cannot be frameless. I have to delete this flag.

**Comment by Jorgen-VikingGod** [comment]
@chaosink sorry, I added this for windows, but forgot to test it on Mac/Linux.
simple #if statement should do the job
