### ISSUE TITLE
Not dark with QT5.15 (LTS)

### ISSUE THREAD

**Issue by marcusbirkin** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#41]
With the new LTS branch of QT (5.15), the theme is no longer dark

- QT 5.15
![image](https://user-images.githubusercontent.com/5006518/82939541-67dc9000-9f8b-11ea-9a11-8c2e6732a768.png)

- QT 5.12.8 (Same platform for reference)
![image](https://user-images.githubusercontent.com/5006518/82939756-b12cdf80-9f8b-11ea-96c1-b722b95b3710.png)

**Comment by Jorgen-VikingGod** [comment]
it's a bug on Qt 5.15:
https://code.qt.io/cgit/qt/qtbase.git/commit/src/widgets/kernel/qapplication.cpp?h=5.15&id=0a93db4d82c051164923a10e4382b12de9049b45
