### ISSUE TITLE
doesnt work on Qt 5.15.*

### ISSUE THREAD

**Issue by kanor** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#47]
The style breaks up with Qt 5.15

qt-everywhere-src-5.15.2.tar.xz
Linux 5.8.0-49-generic #55~20.04.1-Ubuntu SMP Fri Mar 26 01:01:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
![screenshot_linux_frameless_windows_qt_dark_style_enabled png](https://user-images.githubusercontent.com/192241/115358902-6bd65980-a1be-11eb-8a4a-9d875a311971.png)

**Comment by kanor** [comment]
Commenting out the standard palette initialization solves the problem.

`diff --git a/main.cpp b/main.cpp
index 9552ef3..a55ac69 100644
--- a/main.cpp
+++ b/main.cpp
@@ -21,7 +21,7 @@ int main(int argc, char *argv[]) {
 
   // style our application with custom dark style
   QApplication::setStyle(new DarkStyle);
-  QApplication::setPalette(QApplication::style()->standardPalette());
+  //QApplication::setPalette(QApplication::style()->standardPalette());^M
 
   // create frameless window (and set windowState or title)
   FramelessWindow framelessWindow;
`

**Comment by Teddy-van-Jerry** [comment]
Yes, that also works on Qt 6.1!
