### ISSUE TITLE
Any possibility of code exchange?

### ISSUE THREAD

**Issue by antonypro** [Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#54]
@Jorgen-VikingGod: Hi, and thanks for your dark window theme!

I'm here because I'm interested in using your dark theme on my project (https://github.com/antonypro/QGoodWindow) and ask you if you are ok with this, and also ask you if you see any possibility on merge my window with your theme,  i think it may covers #1 and #3 goals.

**Comment by Jorgen-VikingGod** [comment]
hi @antonypro thx for the request. Love your QGoodWindow :+1: 

Sure feel free to embed the DarkStyle to your project/repository - just add somewhere some short credits.

If you have a version with using DarkStyle, let me know - I'm looking forward to test it.

**Comment by antonypro** [comment]
@Jorgen-VikingGod: I'm glad that you like my project.

I'm working hard to create a `QGoodWindow` of yours Dark theme, hence the lack of quick reply to you.

One thing that makes me wonder what is the best method of integration of both projects is the fact that if you accept the merge of your Dark theme with my window you will be introducing a dependency of a stranger into your project, and you maybe not be really happy with this idea.

One option i considered is to maintain your Dark theme in my repository and as you already did, point a link to my project while i do the same with your project.

What do you think? Thanks!

**Comment by Jorgen-VikingGod** [comment]
@antonypro sure, easiest is to embedd the DarkTheme to your repository and mention it :+1:

**Comment by antonypro** [comment]
@Jorgen-VikingGod: It took a long time until i'm able to release a new version of `QGoodWindow` with your dark theme. This is finally done and i think this issue could be closed! 

Thank You!
